/**
 * Professional HTML Email Templates
 * Used for all email communications with customers and admins
 */

export const EmailTemplates = {
  /**
   * Form Submission Email - Sent to admin when customer fills form
   */
  formSubmissionToAdmin: (data: {
    name: string;
    email: string;
    phone?: string;
    subject: string;
    message: string;
    formType: 'contact' | 'get-report' | 'review';
    vehicleType?: string;
    vin?: string;
    submittedAt: string;
  }) => `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #c0392b 0%, #e74c3c 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }
        .header h1 { margin: 0; font-size: 24px; }
        .content { background: #f9f9f9; padding: 30px; border: 1px solid #ddd; border-radius: 0 0 8px 8px; }
        .field { margin: 15px 0; }
        .field-label { font-weight: bold; color: #c0392b; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; }
        .field-value { padding: 10px; background: white; border-left: 3px solid #c0392b; margin-top: 5px; }
        .divider { border: none; border-top: 1px solid #ddd; margin: 20px 0; }
        .message-box { background: white; padding: 15px; border-radius: 6px; border-left: 4px solid #3498db; white-space: pre-wrap; word-break: break-word; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>📋 New ${data.formType === 'contact' ? 'Contact' : data.formType === 'get-report' ? 'Report Request' : 'Review'} Form Submission</h1>
        </div>
        <div class="content">
          <div class="field">
            <div class="field-label">Submission Type</div>
            <div class="field-value">${data.formType === 'contact' ? 'Contact Form' : data.formType === 'get-report' ? 'Get Report Form' : 'Review Submission'}</div>
          </div>
          
          <div class="field">
            <div class="field-label">Submitted By</div>
            <div class="field-value">${data.name}</div>
          </div>
          
          <div class="field">
            <div class="field-label">Email Address</div>
            <div class="field-value"><a href="mailto:${data.email}">${data.email}</a></div>
          </div>
          
          ${data.phone ? `<div class="field">
            <div class="field-label">Phone Number</div>
            <div class="field-value">${data.phone}</div>
          </div>` : ''}
          
          ${data.vehicleType ? `<div class="field">
            <div class="field-label">Vehicle Type</div>
            <div class="field-value">${data.vehicleType}</div>
          </div>` : ''}
          
          ${data.vin ? `<div class="field">
            <div class="field-label">VIN Number</div>
            <div class="field-value">${data.vin}</div>
          </div>` : ''}
          
          <div class="divider"></div>
          
          <div class="field">
            <div class="field-label">${data.subject ? 'Subject' : 'Message'}</div>
            ${data.subject ? `<div class="field-value">${data.subject}</div>` : ''}
          </div>
          
          <div class="field">
            <div class="field-label">Message</div>
            <div class="message-box">${data.message}</div>
          </div>
          
          <div class="field">
            <div class="field-label">Submitted At</div>
            <div class="field-value">${data.submittedAt}</div>
          </div>
          
          <div class="footer">
            <p>This email was automatically generated by CarReaders. Please do not reply to this email.</p>
            <p>Respond directly to the customer's email address above.</p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `,

  /**
   * Order Confirmation Email - Sent to customer after they submit order form
   */
  orderConfirmationToCustomer: (data: {
    orderNumber: string;
    customerName: string;
    packageType: string;
    amount: number;
    currency: string;
    vinOrPlate: string;
    vehicleType: string;
    checkoutUrl?: string;
    estimatedProcessTime?: string;
  }) => `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #27ae60 0%, #2ecc71 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }
        .header h1 { margin: 0 0 5px 0; font-size: 28px; }
        .header p { margin: 0; font-size: 16px; opacity: 0.9; }
        .content { background: #f9f9f9; padding: 30px; border: 1px solid #ddd; }
        .order-box { background: white; padding: 20px; border-radius: 8px; border-left: 4px solid #27ae60; margin: 20px 0; }
        .order-row { display: flex; justify-content: space-between; margin: 10px 0; padding: 8px 0; border-bottom: 1px solid #eee; }
        .order-row:last-child { border-bottom: none; }
        .order-label { font-weight: 600; color: #666; }
        .order-value { font-weight: bold; color: #27ae60; }
        .info-box { background: #e8f8f5; padding: 15px; border-radius: 6px; border-left: 4px solid #27ae60; margin: 20px 0; }
        .info-box h3 { margin: 0 0 10px 0; color: #27ae60; font-size: 16px; }
        .info-box p { margin: 5px 0; font-size: 14px; }
        .cta-button { display: inline-block; padding: 12px 30px; background: linear-gradient(135deg, #27ae60 0%, #2ecc71 100%); color: white; text-decoration: none; border-radius: 6px; margin: 20px 0; text-align: center; font-weight: bold; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>✓ Order Confirmed!</h1>
          <p>Your vehicle report request has been received</p>
        </div>
        <div class="content">
          <p>Hi ${data.customerName},</p>
          
          <p>Thank you for choosing CarReaders! We've successfully received your vehicle report request and it's being processed.</p>
          
          <div class="order-box">
            <div class="order-row">
              <span class="order-label">Order Number:</span>
              <span class="order-value">${data.orderNumber}</span>
            </div>
            <div class="order-row">
              <span class="order-label">Package:</span>
              <span class="order-value">${data.packageType}</span>
            </div>
            <div class="order-row">
              <span class="order-label">Vehicle:</span>
              <span class="order-value">${data.vehicleType}</span>
            </div>
            <div class="order-row">
              <span class="order-label">ID:</span>
              <span class="order-value">${data.vinOrPlate}</span>
            </div>
            <div class="order-row">
              <span class="order-label">Amount:</span>
              <span class="order-value">${data.currency} ${data.amount.toFixed(2)}</span>
            </div>
          </div>
          
          <div class="info-box">
            <h3>📋 What's Next?</h3>
            <p>Your order is waiting for payment. ${data.estimatedProcessTime ? `The complete report will be ready in approximately <strong>${data.estimatedProcessTime}</strong>.` : ''}</p>
            ${data.checkoutUrl ? `<p><a href="${data.checkoutUrl}" class="cta-button">Complete Payment</a></p>` : ''}
          </div>
          
          <div class="info-box">
            <h3>❓ Questions?</h3>
            <p>If you have any questions about your order, please don't hesitate to contact our support team.</p>
          </div>
          
          <div class="footer">
            <p>Thank you for using CarReaders!</p>
            <p>Order Number: ${data.orderNumber}</p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `,

  /**
   * Payment Confirmation Email - Sent to admin when payment is successful
   */
  paymentConfirmationToAdmin: (data: {
    orderNumber: string;
    customerName: string;
    customerEmail: string;
    amount: number;
    currency: string;
    packageType: string;
    transactionId?: string;
    paymentMethod?: string;
    vehicleInfo?: string;
    dashboardUrl?: string;
  }) => `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }
        .header h1 { margin: 0; font-size: 28px; }
        .content { background: #f9f9f9; padding: 30px; border: 1px solid #ddd; border-radius: 0 0 8px 8px; }
        .section { background: white; padding: 20px; border-radius: 6px; margin: 15px 0; border-left: 4px solid #22c55e; }
        .section-title { font-weight: bold; color: #22c55e; margin-bottom: 15px; font-size: 16px; }
        .field { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
        .field:last-child { border-bottom: none; }
        .label { color: #666; font-weight: 600; }
        .value { font-weight: bold; }
        .amount { color: #22c55e; font-size: 18px; }
        .action-button { display: inline-block; padding: 10px 20px; background: #22c55e; color: white; text-decoration: none; border-radius: 6px; margin-top: 10px; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🎉 Payment Received!</h1>
        </div>
        <div class="content">
          <p>Hello Admin,</p>
          <p>A new payment has been successfully processed for a vehicle history report on CarReaders.</p>
          
          <div class="section">
            <div class="section-title">💳 Payment Details</div>
            <div class="field">
              <span class="label">Order Number:</span>
              <span class="value">${data.orderNumber}</span>
            </div>
            <div class="field">
              <span class="label">Amount Paid:</span>
              <span class="value amount">${data.currency} ${data.amount.toFixed(2)}</span>
            </div>
            ${data.transactionId ? `<div class="field">
              <span class="label">Transaction ID:</span>
              <span class="value">${data.transactionId}</span>
            </div>` : ''}
            ${data.paymentMethod ? `<div class="field">
              <span class="label">Payment Method:</span>
              <span class="value">${data.paymentMethod}</span>
            </div>` : ''}
          </div>
          
          <div class="section">
            <div class="section-title">👤 Customer Information</div>
            <div class="field">
              <span class="label">Name:</span>
              <span class="value">${data.customerName}</span>
            </div>
            <div class="field">
              <span class="label">Email:</span>
              <span class="value"><a href="mailto:${data.customerEmail}">${data.customerEmail}</a></span>
            </div>
            <div class="field">
              <span class="label">Package:</span>
              <span class="value">${data.packageType}</span>
            </div>
            ${data.vehicleInfo ? `<div class="field">
              <span class="label">Vehicle:</span>
              <span class="value">${data.vehicleInfo}</span>
            </div>` : ''}
          </div>
          
          ${data.dashboardUrl ? `<p><a href="${data.dashboardUrl}" class="action-button">View in Dashboard</a></p>` : ''}
          
          <div class="footer">
            <p>Payment confirmation has been automatically logged in the system.</p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `,

  /**
   * Payment Confirmation Email - Sent to customer after successful payment
   */
  paymentConfirmationToCustomer: (data: {
    orderNumber: string;
    customerName: string;
    amount: number;
    currency: string;
    packageType: string;
    estimatedDelivery?: string;
    nextSteps?: string;
    supportEmail?: string;
  }) => `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }
        .header h1 { margin: 0 0 5px 0; font-size: 28px; }
        .header p { margin: 0; font-size: 16px; opacity: 0.9; }
        .content { background: #f9f9f9; padding: 30px; border: 1px solid #ddd; border-radius: 0 0 8px 8px; }
        .success-box { background: #eff6ff; padding: 20px; border-radius: 8px; border-left: 4px solid #3b82f6; margin: 20px 0; }
        .timeline { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .timeline-item { display: flex; margin: 20px 0; }
        .timeline-number { display: flex; align-items: center; justify-content: center; width: 40px; height: 40px; background: #3b82f6; color: white; border-radius: 50%; font-weight: bold; margin-right: 15px; flex-shrink: 0; }
        .timeline-content h3 { margin: 0 0 5px 0; color: #3b82f6; }
        .timeline-content p { margin: 0; color: #666; font-size: 14px; }
        .highlight { background: #fef3c7; padding: 15px; border-radius: 6px; border-left: 4px solid #f59e0b; margin: 15px 0; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🎊 Payment Successful!</h1>
          <p>Your order has been confirmed</p>
        </div>
        <div class="content">
          <p>Hi ${data.customerName},</p>
          
          <div class="success-box">
            <p><strong>Thank you for your purchase!</strong> Your payment has been successfully processed and your order is now being prepared.</p>
          </div>
          
          <p style="font-weight: bold; font-size: 18px; margin: 20px 0;">Order Summary</p>
          <div style="background: white; padding: 15px; border-radius: 6px; border: 1px solid #ddd;">
            <p style="margin: 8px 0;"><strong>Order Number:</strong> ${data.orderNumber}</p>
            <p style="margin: 8px 0;"><strong>Package:</strong> ${data.packageType}</p>
            <p style="margin: 8px 0;"><strong>Amount Paid:</strong> ${data.currency} ${data.amount.toFixed(2)}</p>
          </div>
          
          <div class="timeline">
            <p style="font-weight: bold; color: #3b82f6; margin-top: 0; margin-bottom: 20px;">📅 What happens next:</p>
            <div class="timeline-item">
              <div class="timeline-number">✓</div>
              <div class="timeline-content">
                <h3>Order Confirmed</h3>
                <p>Your order has been successfully processed and confirmed.</p>
              </div>
            </div>
            <div class="timeline-item">
              <div class="timeline-number">2</div>
              <div class="timeline-content">
                <h3>Report Generation</h3>
                <p>${data.estimatedDelivery || 'Your report is being generated. This typically takes 12-24 hours.'}</p>
              </div>
            </div>
            <div class="timeline-item">
              <div class="timeline-number">3</div>
              <div class="timeline-content">
                <h3>Delivery</h3>
                <p>You'll receive an email with your complete vehicle history report and a link to view it online.</p>
              </div>
            </div>
          </div>
          
          <div class="highlight">
            <p style="margin: 0;"><strong>📧 Pro Tip:</strong> Check your spam/promotions folder if you don't see our delivery email. Add our email address to your contacts to ensure you receive all updates.</p>
          </div>
          
          ${data.nextSteps ? `<p>${data.nextSteps}</p>` : ''}
          
          <p style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd;">
            <strong>Questions?</strong> ${data.supportEmail ? `You can reply to this email or contact us at <a href="mailto:${data.supportEmail}">${data.supportEmail}</a>` : 'Feel free to reach out to our support team.'}
          </p>
          
          <div class="footer">
            <p>Thank you for using CarReaders. We appreciate your business!</p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `,
};

export default EmailTemplates;
